# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom2/rom2/rom2.xci
# IP: The module: 'rom2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom2/rom2/rom2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom2/rom2/rom2.xci
# IP: The module: 'rom2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom2/rom2/rom2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
