# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vga_constrs.xdc

# IP: C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/mc8051_ram/mc8051_ram/mc8051_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mc8051_ram || ORIG_REF_NAME==mc8051_ram}]

# IP: C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom2/rom2/rom2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom2 || ORIG_REF_NAME==rom2}]

# IP: C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom3/rom3/rom3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom3 || ORIG_REF_NAME==rom3}]
