# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/impl/vga.cache/wt [current_project]
set_property parent.project_path C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/impl/vga.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files C:/Users/hafer/Desktop/VHDL/vga_controller_project/images/Testbild_320x240.coe
add_files C:/Users/hafer/Desktop/VHDL/vga_controller_project/images/SpaceInvader_100x100.coe
add_files C:/Users/hafer/Desktop/VHDL/vga_controller_project/images/custom.coe
add_files C:/Users/hafer/Desktop/VHDL/vga_controller_project/images/SpaceInvader_100x100_transparent.coe
add_files C:/Users/hafer/Desktop/VHDL/vga_controller_project/images/toto.coe
add_files C:/Users/hafer/Desktop/VHDL/vga_controller_project/images/cat_closed.coe
add_files C:/Users/hafer/Desktop/VHDL/vga_controller_project/images/cat_open.coe
add_files C:/Users/hafer/Desktop/VHDL/vga_controller_project/sw/movable_object/build/mc8051_rom.coe
add_files C:/Users/hafer/Desktop/VHDL/vga_controller_project/images/sh.coe
add_files C:/Users/hafer/Desktop/VHDL/vga_controller_project/images/cat_320x240.coe
add_files -quiet c:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/mc8051_ram/mc8051_ram/mc8051_ram.dcp
set_property used_in_implementation false [get_files c:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/mc8051_ram/mc8051_ram/mc8051_ram.dcp]
add_files -quiet c:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom2/rom2/rom2.dcp
set_property used_in_implementation false [get_files c:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom2/rom2/rom2.dcp]
add_files -quiet c:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom3/rom3/rom3.dcp
set_property used_in_implementation false [get_files c:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom3/rom3/rom3.dcp]
add_files -quiet c:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom1/rom1/rom1.dcp
set_property used_in_implementation false [get_files c:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom1/rom1/rom1.dcp]
add_files -quiet C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/mc8051_rom/mc8051_rom/mc8051_rom.dcp
set_property used_in_implementation false [get_files C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/mc8051_rom/mc8051_rom/mc8051_rom.dcp]
read_ip -quiet C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/mc8051_ram/mc8051_ram/mc8051_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/mc8051_ram/mc8051_ram/mc8051_ram_ooc.xdc]
set_property is_locked true [get_files C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/mc8051_ram/mc8051_ram/mc8051_ram.xci]

read_ip -quiet C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom2/rom2/rom2.xci
set_property used_in_implementation false [get_files -all c:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom2/rom2/rom2_ooc.xdc]
set_property is_locked true [get_files C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom2/rom2/rom2.xci]

read_ip -quiet C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom3/rom3/rom3.xci
set_property used_in_implementation false [get_files -all c:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom3/rom3/rom3_ooc.xdc]
set_property is_locked true [get_files C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/generate/rom3/rom3/rom3.xci]

read_vhdl -library xil_defaultlib {
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/addsub_ovcy_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/addsub_cy_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/mc8051_p.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/dcml_adjust_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/control_mem_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/control_fsm_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/comb_mltplr_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/comb_divider_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/alumux_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/alucore_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/addsub_ovcy_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/addsub_cy_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/addsub_core_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/mc8051_tmrctr_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/mc8051_siu_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/mc8051_control_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/mc8051_alu_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/dcml_adjust_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/control_mem_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/control_fsm_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/comb_mltplr_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/comb_divider_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/alumux_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/alucore_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/addsub_core_struc.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/mc8051_tmrctr_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/mc8051_siu_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/mc8051_core_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/mc8051_control_struc.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/mc8051_alu_struc.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/mc8051_top_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/mc8051_core_struc.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mc8051/mc8051_top_struc.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/src_mux/src_mux_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/vga_ctrl/vga_ctrl_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/prescaler/prescaler_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/pattern_gen_2/pattern_gen_2_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/pattern_gen_1/pattern_gen_1_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mem_ctrl_2/mem_ctrl_2_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mem_ctrl_1/mem_ctrl_1_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/io_logic/io_logic_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mem_ctrl_3/mem_ctrl_3_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/src_mux/src_mux_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/top_struc/vga_controller_top_.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/vga_ctrl/vga_ctrl_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/prescaler/prescaler_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/pattern_gen_2/pattern_gen_2_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/pattern_gen_1/pattern_gen_1_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mem_ctrl_2/mem_ctrl_2_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mem_ctrl_1/mem_ctrl_1_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/io_logic/io_logic_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/mem_ctrl_3/mem_ctrl_3_rtl.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/top_struc/vga_controller_top_struc.vhd
  C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/vhdl/top_struc/vga_controller_top_struc_cfg.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/impl/vga.srcs/constrs_1/new/vga_constrs.xdc
set_property used_in_implementation false [get_files C:/Users/hafer/Desktop/VHDL/vga_controller_project/hw/impl/vga.srcs/constrs_1/new/vga_constrs.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top vga_controller_top_struc_cfg -part xc7a35tcpg236-1


write_checkpoint -force -noxdef vga_controller_top_struc_cfg.dcp

catch { report_utilization -file vga_controller_top_struc_cfg_utilization_synth.rpt -pb vga_controller_top_struc_cfg_utilization_synth.pb }
