# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/hafer/Desktop/CHIP1/led_example/impl/led_example.cache/wt [current_project]
set_property parent.project_path C:/Users/hafer/Desktop/CHIP1/led_example/impl/led_example.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib C:/Users/hafer/Desktop/CHIP1/led_example/vhdl/led_example.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/hafer/Desktop/CHIP1/led_example/impl/led_example.srcs/constrs_1/new/led_example_constrs.xdc
set_property used_in_implementation false [get_files C:/Users/hafer/Desktop/CHIP1/led_example/impl/led_example.srcs/constrs_1/new/led_example_constrs.xdc]


synth_design -top led -part xc7a35tcpg236-1


write_checkpoint -force -noxdef led.dcp

catch { report_utilization -file led_utilization_synth.rpt -pb led_utilization_synth.pb }
