# Constraints for 1k ROM test design
# FPGA device/board: Xilinx Artix-7 on Digilent Basys3 board
# Author: Peter Roessler
# Date: 2017-02-02 

create_clock -period 10.000 -name s_clk_i -waveform {0.000 5.000} [get_ports s_clk_i]
set_property PACKAGE_PIN W5  [get_ports s_clk_i]
set_property PACKAGE_PIN T17 [get_ports s_rst_i]
set_property PACKAGE_PIN W19 [get_ports s_inc_fast_i]
set_property PACKAGE_PIN U16 [get_ports {s_led_o[0]}]
set_property PACKAGE_PIN E19 [get_ports {s_led_o[1]}]
set_property PACKAGE_PIN U19 [get_ports {s_led_o[2]}]
set_property PACKAGE_PIN V19 [get_ports {s_led_o[3]}]
set_property PACKAGE_PIN W18 [get_ports {s_led_o[4]}]
set_property PACKAGE_PIN U15 [get_ports {s_led_o[5]}]
set_property PACKAGE_PIN U14 [get_ports {s_led_o[6]}]
set_property PACKAGE_PIN V14 [get_ports {s_led_o[7]}]
set_property PACKAGE_PIN V13 [get_ports {s_led_o[8]}]
set_property PACKAGE_PIN V3 [get_ports {s_led_o[9]}]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports s_clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports s_rst_i]
set_property IOSTANDARD LVCMOS33 [get_ports s_inc_fast_i]
set_property IOSTANDARD LVCMOS33 [get_ports {s_led_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_led_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_led_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_led_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_led_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_led_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_led_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_led_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_led_o[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_led_o[9]}]
